### ISSUE TITLE
Ability to create an Env without providing any image

### ISSUE THREAD

**Issue by mathieu-benoit** [humanitec/preview-envs-action#9]
When I do this:
```
- name: create preview environment
  uses: humanitec/preview-envs-action@v1
  with:
    humanitec-token: ${{ secrets.HUMANITEC_TOKEN }}
    humanitec-org: humanitec-labs
    humanitec-app: dev-docs
    action: create
    github-token: ${{ secrets.GITHUB_TOKEN }}
```
I got this error:
```
Created environment: dev-ephemeral-envs, https://app.humanitec.io/orgs/***/apps/onlineboutique/envs/dev-ephemeral-envs
Created auto-deployment rule for refs/heads/ephemeral-envs and image registry.humanitec.io/***/hello-humanitec
Error: Action failed
Error: HttpError Resource not accessible by integration
```

I think it would be ideal to provide the option to just create a new Env for an App without providing any image. Think about subsequent tasks to deploy Score, etc.

Does that make sense?

**Comment by johanneswuerbach** [comment]
Yes, this was created pre-score and uses automation rules under the hood, but I think those aren't necessary when using score.

For score it might make sense to return the envId as output from the notify action, so it can be used inside the score deploy, wdyt?

**Comment by mathieu-benoit** [comment]
Yes, good point and exactly, having the `envId` as output for `notify` and `create` will be needed.

**Comment by johanneswuerbach** [comment]
Fixed in https://github.com/humanitec/preview-envs-action/pull/16
